### ISSUE TITLE
Make Google Sheet Public ReadOnly

### ISSUE THREAD

**Issue by sachiniyer** [aminoa/nyu-syllabi#3]
All the spreadsheet info seems to be public information. It would be nice to link to the spreadsheet in the Readme to make development easier.

**Comment by aminoa** [comment]
I want to do this but there are some considerations that would need to be resolved. Currently the submitters email is public which may not be desired. The Google Form could be changed to allow the submitter to hide their email (the option I'm leaning towards) or the Google Sheet could have some permissions added to hide the specific column (riskier).

**Comment by sachiniyer** [comment]
You may be able to take advantage of the fact that the intended target in NYU students only, and restrict access to "view within organization".

I am also not sure that anonymous form submission is the right move. I would actually restrict form submission to NYU emails as well. 

To avoid showing emails, I would make a copy of the spreadsheet and use the [importrange](https://support.google.com/docs/answer/3093340?hl=en) function. Alternatively, you might want to just publish some specific columns to the web with the [publish to the web](https://support.google.com/docs/answer/183965?hl=en&co=GENIE.Platform%3DDesktop) feature.

**Comment by aminoa** [comment]
Made the db public via a copy of this sheet using the importrange function: https://docs.google.com/spreadsheets/d/1Im-Kggw4PshixN0X59UXEuug8W83srsuWZGCYn3F-ak/edit?usp=sharing
